name: update changelog

on:
  release:
    types: [released]

permissions: {}

jobs:
  update:
    permissions:
      contents: write
    uses: macocci7/file-selector-prompt/.github/workflows/update-changelog.yml@main
